[package]
name = "duke_rust"
version = "0.1.0"
edition = "2018"

[dependencies]
minimax-alpha-beta = "*"
fstrings = "*"
rand = "*"
paste = "*"
strum = "*"
strum_macros = "*"

crossterm = "*"
tui = { version = "*", default-features = false, features = ['crossterm'] }

[profile.release]
debug = true
