[package]
name = "duke_training"
version = "0.1.0"
edition = "2021"

[dependencies]
duke_rust = { path = ".." }
rand = "0.8"
strum = "0.24"
burn = { version = "0.16", features = ["wgpu", "autodiff", "ndarray"] }
rayon = "1.10"

[[bin]]
name = "duke_training"
path = "src/main.rs"

[[bin]]
name = "benchmark"
path = "src/benchmark.rs"

[[bin]]
name = "train_heuristic"
path = "src/train_heuristic.rs"
